<script setup lang="ts">
const terms = `# Terms of Use for Snapshot

**Last updated: 1 August 2024**

## PREAMBLE

These Terms of Use for snapshot.org ("**Terms**") are entered into between the Prototype Stiftung, a non-profit foundation established under the laws of Switzerland with its registered office in Zug, Switzerland ("**Foundation**") and you as a user ("you", "your" or "**User**") of snapshot.org and/or the snapshot technology as further specified herein ("**Snapshot**").

The Terms, together with any documents incorporated by reference herein, govern your access and use of Snapshot, consisting of the snapshot user interface accessible on snapshot.org and all related tools, applications, smart contracts, and application programming interfaces (APIs) made available. By accessing, interacting with and/or using Snapshot in any form and capacity, you agree to be bound by these Terms.

The Foundation reserves the right to modify these Terms at any time at its sole discretion. In this case, the Foundation will provide notice by changing the “last updated” date above. By continuing to access or use Snapshot, you confirm that you accept the updated Terms and all documents incorporated therein by reference. If you do not agree with these Terms, please immediately cease all use of Snapshot.

## 1. Eligibility and Prohibited Jurisdictions

By accessing or using Snapshot, you represent and warrant that you:

a) have the right, authority, and legal capacity to accept these Terms;
b) will not use Snapshot if the laws of your countries of residency and/or citizenship prohibit you from doing so in accordance with these Terms;
c) are not subject to personal sanctions issued by the UN, US, EU or Switzerland;
d) only access or use Snapshot for your own personal use; and
e) are not accessing Snapshot from one of the countries embargoed or restricted by the Swiss State Secretariat for Economic Affairs (SECO), including, but not limited to: Belarus, Burundi, Central African Republic, Congo, DPRK (North Korea), Guinea, Guinea-Bissau, Iran, Iraq, Lebanon, Libya, Mali, Myanmar (Burma), Republic of South Sudan, Russia, Somalia, Sudan, Syria, Ukraine, Venezuela, Yemen, or Zimbabwe ("**Prohibited Jurisdictions**").

The Foundation reserves the right to technically restrict access to Snapshot and the content provided thereon based on your geographical location.

## 2. Interaction with Snapshot

### 2.1 Connecting Wallet to Snapshot

In order to interact with Snapshot, you must first connect one of the non-custodial third-party wallet solutions listed under the “Connect” tab ("**Wallet**") to Snapshot. Your Wallet stores and manages the private keys (PIK) to your blockchain addresses that were created with the Wallet or manually imported into the Wallet. As these Wallets store your private keys, which are required to sign transactions on-chain, they can be used to execute transactions and publish them to the Ethereum blockchain.

When you connect your Wallet, Snapshot will ask for permission to send Sign Requests (as defined in Section 2.2 below) to the Wallet. During this process, your Wallet will show the blockchain addresses managed by the Wallet that can be connected to Snapshot. You can modify these permissions at any time in the settings of the Wallet. Please note that you can only interact with blockchain addresses that are both managed by the Wallet and connected to Snapshot.

The use of the Wallets is subject to the terms and conditions of the respective provider. The Foundation has no control over the respective PIKs and/or the blockchain addresses that are managed by your Wallet and connected to Snapshot, and no ability to access any assets that are held thereon. You are solely responsible for the security of the Wallet as well as the corresponding private keys and passwords. The Foundation does not assume any responsibility for the connected Wallets, regardless of whether or not they are used to effectuate transactions, and shall not be liable for any damages arising out of or related to your use of the Wallets and/or your inability to connect and/or use the Wallets to execute transactions.

### 2.2 Sign Requests

Once you have connected your Wallet to Snapshot, you can use Snapshot to initiate transactions from your blockchain address by generating standardized transaction messages ("**Sign Requests**"). Sign Requests that are generated by Snapshot are sent to the connected Wallet for approval. To complete the transaction, you must approve the Sign Request by signing the transaction with the connected Wallet. Your Wallet will then display whether the transaction was successful and inform you once it is finalized.

Except when you are voting on Proposals, transactions that are signed with a Wallet are executed on the Ethereum blockchain without any involvement of the Foundation. Snapshot does not execute transactions on your behalf and does not control the execution of transactions initiated by you. You are fully responsible for all inputs you make while using Snapshot.

## 3. Features

Snapshot offers the following features (together "**Features**"):

- **Spaces** (see Section 4 below)
- **Creation and Voting on Proposals** (see Section 5 below)
- **Archiving on IPFS** (see Section 6)
- **Boost Application ("Boost App";** see Section 8 below)

The Foundation reserves the right to modify, suspend, or discontinue, temporarily or permanently, Snapshot (or any Feature or part thereof) at any time in its sole discretion without liability.

## 4. Spaces

Snapshot is a platform that allows Users to create and manage spaces ("**Spaces**") for decentralized autonomous organizations and decentralized communities (together "**DAOs**"). The Space is a dedicated area where such DAO’s community ("**Community**") can participate in the decentralized governance of DAOs by creating, managing, and participating in gasless and off-chain proposal-based voting.

Any User can create a new Space on the Snapshot platform tailored to their specific DAO's needs and branding. The creator of the Space becomes the administrator of such Space and can customize the Space with specific settings, roles, and permissions to allow the Community to engage in governance activities.

Within each Space, Community members can:

- submit proposals for various decisions or actions they want the DAO to consider;
- participate in proposals by voting.

### 4.1 Creation, Modification, and Deletion of Spaces

Creating a Space requires an Ethereum Name Service ("**ENS**") domain and a Wallet. When creating a Space, you will be required to define the profile of your Space (e.g., name, description, profile, etc.), specify the Permissions (as defined below), the Voting Strategies (see Section 17), and Validation Strategies (see Section 4.3).

As part of the creation of a Space, you will be able to assign a set of permissions ("**Permissions**") to Wallets in relation to the management of Spaces and Proposals. You will be able to choose between the following Permissions:

- **Controller**: The Controller of your Space has full control over the Space settings, including managing the list of Admins. The Controller will be able to delete your Space.
- **Admin(s)**: The Admins can edit the Space’s settings and details such as name, avatar, banner, description, and validation setting but not the list of Admins. Admins can hide the Proposals from the main view but do not have the right to delete it permanently.
- **Moderator**: The Moderator can create, edit, archive, and manage Proposals within the Space.
- **Author**: The Author can create Proposals regardless of their voting power and the Proposal validation strategy set for the Space. This allows a wider range of users to submit Proposals for consideration by the community.

After the creation of the Space, only the Controller can change the settings for your Space (e.g., sub-spaces; additional voting requirements such as voting delay, voting period, and quorum; shielded voting; delegation; custom domain; skin; treasuries; plugins, etc.) or delete your Space at any time.

### 4.2 Voting Strategies

Voting strategies ("**Voting Strategies**") calculate the voting power of each Wallet that has voted on a Proposal. The [Controller or Author] will be able to select between the following Voting Strategies (non-exhaustive list):

- **Token Weighted Voting**: The voting power of each Wallet is weighted by the amount of the relevant governance tokens held by that wallet.
- **One Person One Vote**: Each Wallet has one vote. Token holdings are not relevant for the calculation of the voting power.
- **Custom Setup**: You can combine up to eight Voting Strategies. You can use the Voting Strategies created by members of the Community or design your own custom Voting Strategy. You can either whitelist specific Wallets to be able to vote or allow any Wallet to vote.

Users are encouraged to thoroughly understand how each Voting Strategy works and its potential impact on governance outcomes before participating in voting or creating Proposals.

Voting Strategies should be considered in conjunction with other Space settings such as Proposal validation rules and voter eligibility criteria.

The Space [Controller or Author] should ensure that the combination of Voting Strategies and other settings aligns with the desired governance model and objectives of the Space. We do not guarantee the accuracy, reliability, or suitability of any information, content, or Voting Strategies provided by any Users or third parties. Further, Snapshot does not endorse, verify, or take responsibility for actions, decisions, or outcomes resulting from the use of any one or more Voting Strategies.

### 4.3 Validation Strategies

Validation strategies ("**Validation Strategies**") define if a Wallet holding a specific token can vote or create a Proposal in a specific Space. You can set specific Validation Strategies that a Wallet must meet to be eligible to create or vote on Proposals. You will be able to select between the following Validation Strategies (non-exhaustive list):

- **Proposal Validation**: You determine whether a particular Wallet can create a new Proposal in Space.
- **Voting Validation**: You determine whether a specific Wallet can participate in the voting process (i.e., vote on Proposals).

## 5. Proposals and Voting

### 5.1 Overview

The proposals ("**Proposals**") allow the DAO's Community to participate in the decentralized decision-making process by creating and voting on Proposals without the payment of any gas fees on the underlying blockchain network.

### 5.2 Creation, Modification, and Deletion of Proposals

Provided you have the necessary Permissions (see Section 4.1), you can create a Proposal by connecting your Wallet. When creating a Proposal, you will be required to define the title of the Proposal, the description of the Proposal, the relevant details and content of the Proposal, Voting Types (as defined in Section 5.3), the voting options, the start and duration of the Proposal.

As long as the voting period of the Proposal has not started, you can edit and delete the Proposal or its details.

### 5.3 Voting Types

Voting types ("**Voting Types**") define how Wallets can cast their votes on Proposals and how the result is calculated. You will be able to select between the following Voting Types for your Proposal (non-exhaustive list):

- **Single Choice Voting**: Each Wallet can select only one option (e.g., ‘yes’ or ‘no’). The results will reflect these votes as percentages of the total voting power of all Wallets that have voted on the Proposal.
- **Weighted Voting**: Each Wallet can spread their voting power across any number of choices from one to all. Their voting power will be divided between their chosen options according to how much weight they attribute to each option by increasing or decreasing the voting power fraction.
- **Approval Voting**: Each Wallet can select (approve) any number of choices; each selected choice will receive equal voting power.
- **Quadratic Voting**: Each Wallet can spread their voting power over several multiple options. Each Wallet's influence is calculated by taking the square root of their voting power for each option.
- **Ranked Choice Voting (Instant Runoff Voting)**: Each Wallet must rank all choices in a desired order.
- **Basic Voting**: Each Wallet can select one of three options: “for”, “against”, and “abstain”.

### 5.4 Voting on Proposals

#### Voting Process

You can only vote for a Proposal if you connect your Wallet and you are in compliance with the Voting Strategies (see Section 4.2) and the Validation Strategies (see Section 4.3) of the Space and the Proposals.

By voting on a Proposal, you are required to vote with your Wallet. The signature process with your Wallet does not require the payment of any gas fees to the underlying blockchain network as the casting of a vote is gasless.

You agree that you will not vote on Proposals whose content may be illegal, fraudulent, offensive, abusive, indecent, harmful, defamatory, obscene, or menacing, abusive, threatening, objectionable, invasive of privacy, in breach of confidentiality toward a third party, infringe intellectual property rights, or which may threaten the safety of any User or third party. Snapshot reserves the right to hide such Proposals. Snapshot is not liable for the content of Proposals.

#### Delegation of Voting Power

You can delegate your voting power to other Wallets. When you delegate your voting power, you have to enter the Wallet to which you want to delegate and specify whether the delegation is limited to a specific Space. If no Space is selected, the delegation applies to all Spaces on Snapshot.

## 6. Archiving on IPFS

By using the Features, you acknowledge that information which is published on Snapshot, including but not limited to the Proposals’ content and voting results, will be permanently and publicly stored on the InterPlanetary File System (IPFS) and will be available to anyone, and that neither we nor any third party will have the power to restrict access to the data or delete such data stored on IPFS. Please be aware that the permanence of data on IPFS means that even if the original data is removed from Snapshot, copies of the data may still exist and be accessible on IPFS. While Snapshot facilitates the creation and voting process for Proposals, Snapshot does not have control over any data stored on IPFS and does not store any data on IPFS but rather relies on the decentralized nature of IPFS for storage and retrieval.

This information can also contain data which is considered personal data relating to an identified or identifiable natural person. If you want to ensure that your or third party’s privacy rights are not affected in any way, you should not use our Features as certain rights arising out of data protection laws may not be fully available or exercisable by you or us due to the technological infrastructure of IPFS.

By using Snapshot, you acknowledge and accept the implications of data permanence on IPFS. You should carefully consider the content you include in Proposals and your voting actions as they cannot be undone or removed once stored on IPFS.

## 7. No Influence of Foundation over Spaces and Proposals

The execution of Proposals lies at the discretion of the DAOs. The Foundation – as well as any other private individual and/or legal entity related to the Foundation – has neither access to nor any other possibility to control and/or influence Spaces and their corresponding Proposals created and voted on by the Community.

## 8. Boost App

### 8.1 Overview

The Boost App is a smart contract-based application on the Ethereum blockchain that allows DAOs and their Communities to incentivize participants in the governance of the DAO by defining events ("**Boost Events**") that trigger rewards in the DAO's own governance token ("**Governance Rewards**") for DAO participants ("**Governance Participants**").

### 8.2 Creation of Boost Events

When you create a Boost Event, you define the amount of Governance Rewards, the conditions ("**Conditions**"), and the Distribution Criteria (as defined in Section 8.3) under which Governance Participants can earn Governance Rewards during an eligible period ("**Boost Term**").

Once you lock the Governance Rewards in the Boost App and pay the fees set out in Section 8.5, you will receive an NFT, and your Boost Event will start and be visible in the DAO’s space. You will not be able to modify and/or cancel your Boost Event once it has started.

By creating a Boost Event, you accept and understand that:

- the Governance Participants will have two weeks following the Boost Term ("**Claim Period**") to claim the Governance Rewards;
- any Governance Rewards collected by the Governance Participants cannot be reclaimed by you;
- DAOs may be able to block your Boost Event on their Space if your Boost Event rewards Governance Participants for voting on specific Proposal outcomes;
- the Governance Rewards will be locked in the Boost App until the end of the Claim Period.

### 8.3 Distribution Criteria

You will be able to select between the following distribution criteria ("**Distribution Criteria**") for your Boost Event:

- **Weighted Criteria**: The weighted criteria ("**Weighted Criteria**") allow Governance Rewards to be distributed to Governance Participants that have satisfied the Conditions ("**Eligible Participants**") in proportion to their voting power within the DAO. You can also set a maximum limit on the amount of Governance Rewards per Eligible Participant to prevent a single Eligible Participant from receiving a disproportionate amount of the Governance Rewards.
- **Randomness Criteria**: The randomness criteria ("**Randomness Criteria**") uses the Ethereum blockchain’s RANDAO-based RNG algorithm to randomly select one or multiple Eligible Participants based on the Eligible Participant’s voting power within the DAO. A maximum voting power limit may be set to prevent any excess voting beyond that limit from being taken into account by the Randomness Criteria.

### 8.4 Collection of Governance Rewards

Once a Governance Participant has complied with the Conditions, they will be able to collect the relevant Governance Rewards from the Boost App in accordance with the Distribution Criteria.

You accept and acknowledge that the Foundation will rely on the authenticity and integrity of your Conditions and Distribution Criteria set by you and does not conduct any due diligence or similar investigations as to the factual circumstances of the compliance with the Conditions and Distribution Criteria. The Foundation will not assume any liability associated with the (non-)compliance with the Conditions and Distribution Criteria, including but not limited to issues arising from fraud, misconduct of Governance Participants, and/or defects in the Distribution Criteria, etc.

At the end of the Claim Period, you will be able to unlock the remaining Governance Rewards by transferring the NFT to the Boost App.

### 8.5 Fees

The creation of Boost Events (i.e., when locking Governance Rewards in the Boost App) is subject to the payment of the following fees:

- **ETH Fees**: You will be required to pay us a fee in ETH as displayed on the Boost App.
- **Governance Reward Fees**: You will be required to pay us a fee in Governance Rewards as displayed in the Boost App. This fee will be deducted from the total amount of locked Governance Rewards at the time of creation of the Boost Event.

### 8.6 Gas Fees

All interactions with the Boost App require the payment of a transaction fee ("**Gas Fee**"), which is paid to the validators of the Ethereum blockchain. The Gas Fee required to execute a transaction depends on the activity on the Ethereum blockchain and is entirely outside of the control of the Foundation. By using the Boost App to initiate transactions and generate Sign Requests, you acknowledge and agree that Gas Fees are non-refundable under any circumstances.

## 9. Risks

By accessing or using Snapshot, you understand and accept the risks connected to the Boost App. In particular, but not exhaustively, you understand the inherent risks listed hereinafter:

- the Foundation does not control the public blockchains that Users are interacting with, nor any smart contracts and protocols that may be integral to Users’ ability to complete transactions on these public blockchains. On-chain transactions may be irreversible, and accordingly, losses due to fraudulent or accidental transactions may not be recoverable. Some transactions shall be deemed to be made when recorded on a public ledger, which is not necessarily the date or time that the User initiated the transaction.
- the Foundation is not responsible for the title, value, validity, or genuineness of any of the Governance Rewards (or any evidence of title thereto);
- the nature of Governance Rewards as digital assets and the Boost App may lead to an increased risk of fraud or cyberattacks and may mean that technological difficulties experienced may lead to limited access to and use of the Boost App;
- The Foundation reserves the right to stop any Boost Events for any reason.

## 10. Intellectual Property Rights

While the rights in Snapshot are held by the Foundation, the Foundation has published the source code of Snapshot ("**Snapshot Code**") on its public GitHub repository and released it under the MIT open-source license. You are free to use the Snapshot Code to create another Snapshot for any other purpose.

## 11. Your Representations and Warranties

By accepting these Terms, you warrant and represent that:

- you will not create or manage Spaces for any purpose that is fraudulent, illegal, offensive, defamatory, or otherwise tortious or unlawful, including but not limited to illegal gambling, money laundering, fraud, blackmail, extortion, ransoming data, the financing of terrorism, intellectual property infringement, or violent or abusive activities. The Foundation reserves the right to hide such Spaces on Snapshot;
- you will not create, submit, and vote on any Proposal whose content may be illegal, fraudulent, offensive, abusive, indecent, harmful, defamatory, obscene, or menacing, abusive, threatening, objectionable, invasive of privacy, in breach of confidentiality toward a third party, infringing intellectual property rights, or which may threaten the safety of any User or third party. Snapshot reserves the right to hide such Proposals on Snapshot. Snapshot is not liable for the content of Proposals.
- you have provided all necessary notices to and obtained all necessary consents from the relevant parties for the collection and processing of their personal data for the purposes including but not limited to the archiving of the relevant personal data at IPFS;
- any Governance Rewards locked in the Boost App are: (a) good, clean, clear, and are of non-criminal origin; (b) completely free and clear of any liens or encumbrances of any kind, of any rights of third-party interests; and (c) have no origins that may be connected to any breach of money laundering regulations whatsoever as defined in the jurisdiction of origin or internationally;
- any Governance Rewards qualify as utility tokens within the meaning of Swiss financial market regulations and are not payment instruments, means of payment, payment tokens, and/or securities under any applicable laws;
- you will not pretend to be another person or entity or act on behalf of a third party;
- you will not provide false, inaccurate, or misleading information;
- you have done sufficient research before making any decisions to create a Boost Event, lock, and/or collect any Governance Rewards;
- you are legally permitted to receive, hold, and make use of Governance Rewards in your jurisdiction.
- you have the sole control over your Wallet.
- you will not upload, distribute, or otherwise make available through Snapshot any unlawful, defamatory, harassing, abusive, fraudulent, obscene, or otherwise objectionable content;
- you will not upload, distribute, or otherwise make available through Snapshot any content that infringes intellectual property rights of any party;
- you will not distribute malware, viruses, worms, defects, or other items of a destructive or captive nature;
- you will not use Snapshot for any illegal activity, including without limitation terrorism, tax evasion, or money laundering;
- you will not facilitate transactions involving individuals sanctioned by the Swiss, US, or any European government;
- you will not use Snapshot to carry out any financial activities subject to registration or licensing, including but not limited to creating, selling, or buying securities, commodities, options, or debt instruments;
- you will not use Snapshot to create, sell, or buy tokens or other items that give other users rights to participate in an ICO or any securities offering or that are redeemable for securities, commodities, or other financial instruments;
- you will not defame, abuse, extort, harass, stalk, threaten, or otherwise violate or infringe the legal rights of others, including without limitation privacy rights and intellectual property rights;
- you will not remove any copyright, trademark, or other proprietary rights notices contained in or on Snapshot or any part of it;
- you will not use any data mining, robot, spider, crawler, scraper, script, browser extension, offline reader, or other automated means or interface not authorized by us to access Snapshot, extract data, or otherwise interfere with or modify the rendering of service pages or functionality;
- you will not attempt to circumvent any fees charged by the Foundation;
- you will not use Snapshot in a manner that breaches or causes the breach of any applicable export and re-export control laws and regulations.

## 12. Disclaimers & Limited Warranty

The Foundation does not guarantee that Snapshot is free from defects, errors, bugs, and security vulnerabilities or that it will be available at any time. The access to and use of Snapshot is made at your own risk.

The Foundation gives no assurance that any functionalities and Features of Snapshot will satisfy your requirements or provide the intended results or meet any performance or reliability standards. You understand and agree that Snapshot is provided on an “as is” and “as available” basis and that Snapshot expressly disclaims all warranties or conditions of any kind, whether express, implied, statutory, or otherwise.

The Foundation makes no warranties as to the security, functionality, or availability of the Boost App, including but not limited to the corresponding smart contracts and Boost Events, as it may contain bugs, defects, or errors (including any bugs, defects, or errors relating to or resulting from the display, manipulation, processing, locking, transfer, or distribution of Governance Rewards) that may materially and adversely affect the use or functionality of the Boost App or any product or system containing or used in conjunction with the Boost App.

The Governance Rewards exist only by virtue of the ownership record maintained in the associated blockchain (e.g., Ethereum blockchain). Any transfers occur on the Ethereum blockchain. The Foundation and/or any other Foundation Party (as defined in margin 46) cannot effect or otherwise control the transfer of title or right in any Governance Rewards.

## 13. Limitation of Liability

The liability of the Foundation is limited to direct damages arising out of acts of intent and gross negligence. Any liability for indirect damages or consequential damages, including loss of profit and/or damages arising out of negligent conduct, is expressly excluded. In particular, the Foundation does not assume any responsibility for Snapshot (or any feature or part thereof) and shall not be liable for any damages arising out of or related to your use of Snapshot, including but not limited to your creation and management of Spaces, submission, voting, and execution of Proposals, use of Boost Events, or your inability to collect and/or distribute Governance Rewards.

## 14. Indemnification

You agree to the fullest extent permitted by applicable law to indemnify, defend, and hold harmless the Foundation and the Foundation Parties from and against all actual or alleged any claims, damages, awards, judgments, losses, liabilities, obligations, penalties, interests, fees, expenses (including without limitation attorneys’ fees and expenses), and costs (including without limitation court costs, costs of settlement, and costs of pursuing indemnification and insurance) of every kind and nature whatsoever, whether known or unknown, foreseen or unforeseen, matured or unmatured, or suspected or unsuspected, in law or equity, whether in tort, contract, or otherwise ("**Claims**") that are caused by, arise out of, or are related to:

- your use or misuse of Snapshot;
- your violation or breach of any term of these Terms, applicable law;
- your violation of the rights of or obligations to a third party, including another User or third-party; and
- your negligence or willful misconduct.

You agree to promptly notify the Foundation of any Claims and cooperate with the Foundation and all past, present, and future employees, officers, council members, directors, contractors, consultants, founders, suppliers, vendors, service providers, subsidiaries, affiliates, agents, representatives, predecessors, successors, and assignees of the Foundation ("**Foundation Parties**") in defending such Claims. You further agree that the Foundation, respectively the Foundation Parties, shall have control of the defense or settlement of any Claims. This indemnity is in addition to and not in lieu of any other indemnities as set forth in a written agreement between you and the Foundation, respectively the Foundation Parties.

## 15. Privacy Notice and Cookie Declaration

Please refer to our Privacy Notice to understand how we collect and use and disclose your personal data as well as our Cookie Declaration to understand how we use cookies and how you can change your consent to their use.

## 16. Miscellaneous

### 16.1 User Feedback

The Foundation appreciates and encourages you to provide feedback to Snapshot. If you provide feedback, you agree that the Foundation is free to use it and may permit others to use it without any restriction or compensation to you.

### 16.2 Tax

It is your sole responsibility to seek appropriate tax advice to comply with any applicable tax and duties or similar obligations in whichever jurisdiction and to assess the tax impact of the use of Snapshot, including the Boost App, and the use of the features offered thereon.

The User has no right to request a refund of any taxes, duties, or charges from the Foundation.

All fees payable to the Foundation are to be understood as exclusive of Swiss VAT. If Swiss VAT is due by the Foundation, the Foundation is free to charge the Swiss VAT to the User.

### 16.3 Entire Agreement and Severability

These Terms contain the entire agreement between the Foundation and the Users regarding the subject matter hereof and supersedes all understandings and agreements, whether written or oral. If any provision of these Terms is invalid, illegal, or unenforceable in any jurisdiction, such invalidity, illegality, or unenforceability shall not affect any other provision of these Terms or invalidate or render unenforceable such provision in any other jurisdiction. Upon such determination that any provision is invalid, illegal, or unenforceable, these Terms shall be modified to effectuate the original intent of the Parties as closely as possible.

### 16.4 Governing Law and Jurisdiction

These Terms shall be governed and construed in accordance with the substantive laws of Switzerland, without regard to conflict of law rules or principles (whether of Switzerland or any other jurisdiction). The application of the United Nations Convention on Contracts for the International Sale of Goods shall be excluded.

Any dispute arising out of or in conjunction with these Terms shall be submitted to the exclusive jurisdiction of the ordinary courts of the city of Zug, Switzerland.`;
</script>

<template>
  <div>
    <BaseContainer class="mb-[40px] max-w-[880px]">
      <BaseMarkdown :body="terms" />
    </BaseContainer>
  </div>
</template>
